[package]
name = "flexui-examples"
version = "0.0.1"
edition = "2021"

[dependencies]
flexui = { path = "../flexui" }
image = { workspace = true }
tray-icon = { workspace = true }

[build-dependencies]
winresource = { version = "0.1.31", default-features = false }
zip = { version = "2", default-features = false, features = ["deflate"] }
