[package]
name = "flexui-macos"
version = "0.0.1"
edition = "2021"

[dependencies]
flexui-gfx = { workspace = true }
flexui-core = { workspace = true }
flexui-svg = { workspace = true }
flexui-native-menu = { workspace = true }
objc2 = { workspace = true }
objc2-foundation = { workspace = true }
objc2-app-kit = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10"
core-graphics = "0.24"
core-text = "21"
