[package]
name = "flexui-gallery"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
flexui = { version = "0.1.0", path = "../flexui" }
minreq = { version = "2.14", features = ["https-rustls"] }

[build-dependencies]
zip = { version = "2", default-features = false, features = ["deflate"] }
